### ISSUE TITLE
uglify after import

### ISSUE THREAD

**Issue by sandrina-p** [ifandelse/gulp-imports#7]
Hey, i'm moving away from Koala App, and one the features I loved about koala is the imports on javascript files, so your plugin sounds awesome. I try it and worked. The problem is: After the import i also add gulp-uglify and it gives a error. I even try to uglify the .min.js after the import but it didn't work neither.

This is the gulp.task:

```
gulp.task('scripts', function(){
    gulp.src([
            'testgulp/**/*.js', '!testgulp/**/_*.js', '!testgulp/**/*.min.js'
        ])
        .pipe(gulpImports())
        .pipe(rename({ suffix: '.min' }))
        .pipe(gulp.dest(function(file) { return file.base; }));

    gulp.src('testgulp/**/*.min.js')
        .pipe(uglify());
});
```

And on terminal i got this:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/gulp-uglify/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Applications/MAMP/htdocs/git/personal-sandrina-p/_main/v3/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

Thanks :)

**Comment by cdll** [comment]
@sandrina-p i dont know whats wrong with ur gulp task, but i think it will work fine as:
````
gulp.task('scripts', function(){
  gulp.src([
    'testgulp/**/*.js'
    ,'!testgulp/**/_*.js'
    ,'!testgulp/**/*.min.js'
  ])
  .pipe(gulpImports())
  .pipe(uglify());
  .pipe(rename({ suffix: '.min' }))
  .pipe(gulp.dest(function(file) {
    return file.base;
  }));
});
````

**Comment by sandrina-p** [comment]
@cdll i already fixed the issue, it qas because i was using ES6 without babel. i installed babel and added it to the task and it worked :D

**Comment by jcklpe** [comment]
@sandrina-p  What do you mean you added babel to the task? As in you just piped it through the gulp-babel plugin? 

I seem to be having a similar problem except it has to do with sourcemaps. When I put uglify after import it's fine, but I want to uglify  after source map so that I can get allt he correct source map information.

**Comment by sandrina-p** [comment]
@jcklpe this was a long time ago and I don't remember :/
